#!/bin/bash

#we need to give the path of directory which we need to backup and we need to create variable for it

source_directory=("/home", "/ubuntu")

# we need to mention where we are going to  ackup this data 

Destination="/backup"

# now we need to give date format for the snapshots we will going to backup 

Timestamp=$(date + "%Y%m%d_%H%M%S")

# now we need to create a log file where all standard input and error are going to be stored

logfile=("/var/log/backup_$Timestamp.log")

# now we need to create the destination directory including parent directory

mkdir -p "$Destination/$Timestamp"

# we need to synchronize the files now and need to append files and delete removed files

for SRC in "${source_directory[@]}"; do

rsync -a --delete "$SRC" "$$Destination/$Timestamp" &>> "$logfile"

done

# we need to check logs which are older and we can delete those

find "$destination" -maxdepth 1 -type d -mtime +7 -exec rm -rf {} \; &>> "$logfile"

# now  we need to share report of the backup over mail

if grep -q "rsync error" "$logfile"; then
    mail -s "Backup Failed on $(hostname)" admin@example.com < "$logfile"
    exit 1
else
    mail -s "Backup Successful on $(hostname)" admin@example.com < "$logfile"
    exit 0
fi
